services:
  snel-proto:
    build: .
    container_name: snel-proto
    ports:
      - "3399:3000" # h√¥te:conteneur (port 3399 sur le serveur OVH)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - snel-network

networks:
  snel-network:
    driver: bridge
    name: snel-network

